[package]
name = "edid-info"
version = "0.2.0"
edition = "2024"
license = "MIT"
description = "Lightweight Rust library for reading EDID data"
repository = "https://github.com/SzilvasiPeter/edid-info"
readme = "README.md"
keywords = ["edid", "display", "monitor", "no-std", "zero-dependency"]
categories = ["parsing", "hardware-support", "multimedia"]

[[bin]]
name = "check-bytes"
path = "tools/check-bytes.rs"

[[test]]
name = "base"
path = "tests/base/mod.rs"

[[test]]
name = "descriptor"
path = "tests/base/descriptor/mod.rs"

[[test]]
name = "cta"
path = "tests/extensions/cta/mod.rs"

[[bench]]
name = "parse"
path = "benches/parse.rs"

[dependencies]

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
all = "deny"
pedantic = "deny"
nursery = "deny"
cargo = "deny"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true
